### ISSUE TITLE
需要修复链接跳转问题

### ISSUE THREAD

**Issue by FQUVCT** [SketchFlaMe/SFM#1]
![Screenshot_2022-11-08-21-13-32-822_com.android.browser.jpg](https://user-images.githubusercontent.com/97376854/200574148-81163c37-443a-4317-ac20-5a127279ea11.jpg)

**Comment by SketchFlaMe** [comment]
烦唉
这怎么修啊（恼）

**Comment by SketchFlaMe** [comment]
到时候加个新页面用来跳转好了

**Comment by FQUVCT** [comment]
开摆！

**Comment by SketchFlaMe** [comment]
> 开摆！

开摆！

**Comment by SketchFlaMe** [comment]
已完成部分更新 目前可通过链接进入

**Comment by SketchFlaMe** [comment]
已删除页面中的错误链接
